### ISSUE TITLE
Squawker not saving account credentials when it is closed

### ISSUE THREAD

**Issue by italoghost** [j-fbriere/squawker#208] opened 2024-02-16 01:08 UTC
Hi!

I have successfully added my account to Squawker, but when I close the app, it vanishes and I have to insert it again.

It even happens when I have more than one instance of the app running (like when you open the app through another app).

I am on the latest release: 3.7.3

**Comment by j-fbriere** [comment] 2024-02-16 04:27
Try the following test.
- Make sure that no Squawker is open
- Open Squawker, then go to Settings / Account
- Click on the plus icon, add an account and click save. The added account should be visible in the page.
- Close Squawker
- Open Squawker, then go to Settings / Account

Do you see the account that you added in the page?

**Comment by italoghost** [comment] 2024-02-16 04:56
No, I don't! As soon as I close the app and open it again, the account is missing

**Comment by Saroumane** [comment] 2024-02-16 15:09
I reproduce this bug with 3.7.3

**Comment by j-fbriere** [comment] 2024-02-16 16:46
@italoghost @Saroumane What is your device and Android version?

**Comment by Undisputed00x** [comment] 2024-02-16 16:56
Having same issue - Pixel 6 Pro - GrapheneOS latest version - Squawker latest ci build

**Comment by Saroumane** [comment] 2024-02-16 17:00
Pixel 6a, latest GrapheneOS (based on Android 14), Squawker 3.7.3

**Comment by italoghost** [comment] 2024-02-16 17:19
Samsung S20 FE 5G, Android 13

**Comment by j-fbriere** [comment] 2024-02-16 20:02
After closing Squawker, if you reopen Squawker and the account you added previously disappeared, please export the data with Settings / Data / Export.

Then open the exported file. In the exported file, under the **twitterTokens** node do you see child nodes? 
If so are there one or more nodes with **guest** = 1?

If you don't know how to view an exported file, install and use the **Json File Viewer Reader Editor** application.

**Comment by Undisputed00x** [comment] 2024-02-16 20:47
> After closing Squawker, if you reopen Squawker and the account you added previously disappeared, please export the Squawker data with Settings / Data / Export.
> 
> Then open the exported file. In the exported file, under the **twitterTokens** node do you see child nodes? If so are there one or more nodes with **guest** = **0**?
> 
> If you don't know how to view an exported file, install and use the **Json File Viewer Reader Editor** application.

I see 3 same id_str child nodes which also have guest = 0

**Comment by j-fbriere** [comment] 2024-02-16 20:58
> I see 3 same id_str child nodes which also have guest = 0

Ok so it means that there is "something" in each of these child nodes that make Squawker dismiss them when opening.
Here the structure of a child node whit guest = 0 :
```
{
  "guest": 0,
  "id_str": "xxxx",
  "screen_name": "xxxx",
  "oauth_token": "xxxx",
  "oauth_token_secret": "xxxx",
  "created_at": "xxxx",
  "profile": {
    "username": "xxxx",
    "password": "xxxx",
    "created_at": "xxxx",
    "name": "xxxx",
    "email": "xxxx",
    "phone": "xxxx",
  }
}
```
Can you tell me precisely which element(s) have a null or empty value ("")?

**Comment by Undisputed00x** [comment] 2024-02-16 21:39
> > I see 3 same id_str child nodes which also have guest = 0
> 
> Ok so it means that there is "something" in each of these child nodes that make Squawker dismiss them when opening. Here is the structure of a child node with **guest** = **0** :
> 
> ```
> {
>   "guest": 0,
>   "id_str": "xxxx",
>   "screen_name": "xxxx",
>   "oauth_token": "xxxx",
>   "oauth_token_secret": "xxxx",
>   "created_at": "xxxx",
>   "profile": {
>     "username": "xxxx",
>     "password": "xxxx",
>     "created_at": "xxxx",
>     "name": "xxxx",
>     "email": "xxxx",
>     "phone": "xxxx",
>   }
> }
> ```
> 
> Can you tell me precisely which element(s) are missing or have a null or empty value ("")?

```
profile:"null"
```

**Comment by NeanderthalNinny** [comment] 2024-02-16 23:50
Hello, I'm experiencing the same issue (Squawker not saving credentials). I'm running Android 14, Google Pixel 8 Pro on Squawker v3.7.3+300013903. 

Under twitterTokens I have one node with guest = 0

Here is the json output:

{
  "guest": 0,
  "id_str": "xxxx",
  "screen_name": "xxxx",
  "oauth_token": "xxxx",
  "oauth_token_secret": "xxxx",
  "created_at": "xxxx",
  "profile": null
}

I hope this helps. 
NN

**Comment by italoghost** [comment] 2024-02-17 17:22
I have three "guest = 0" nodes and all of them have `profile: "null"`

**Comment by j-fbriere** [comment] 2024-02-17 21:11
Could you please do another test.
Do the following steps:
- Make sure that no Squawker is open
- Open Squawker, then go to Settings / Account
- Tap on the Plus icon, add your account information and tap on the Save button.
  ==> Please confirm that the added account is visible in the page.
- Go to Settings / Data and select Export then tap on the Save icon.
- Open the exported file. In the exported file, under the **twitterTokens** node please show in details the child nodes where **guest** = **0** (mask the personal information).
  This should look like:
```
{
  "guest": 0,
  "id_str": "xxxx",
  "screen_name": "xxxx",
  "oauth_token": "xxxx",
  "oauth_token_secret": "xxxx",
  "created_at": "xxxx",
  "profile": {
    "username": "xxxx",
    "password": "xxxx",
    "created_at": "xxxx",
    "name": "xxxx",
    "email": "xxxx",
    "phone": "xxxx",
  }
}
```

If you don't know how to view an exported file, install and use the **Json File Viewer Reader Editor** application.

Than you

**Comment by edjocute** [comment] 2024-02-18 10:29
For me, signing in with the username instead of the email address fixes the disappearing account issue.

**Comment by Undisputed00x** [comment] 2024-02-18 13:28
> For me, signing in with the username instead of the email address fixes the disappearing account issue.

This works

**Comment by italoghost** [comment] 2024-02-18 14:04
@edjocute this is interesting. I was signing in with my username, but I was adding the "@". When I just used my username, without the "@", it worked. 

But then it started spamming the same account

**Comment by Saroumane** [comment] 2024-02-18 14:37
I always use the username ( without the "@"), and it always disappear if I quit the app.

**Comment by cerega000** [comment] 2024-02-20 15:37
All of my usernames start with an uppercase letter. Inputting them entierly in lowercase fixed this issue for me.

**Comment by j-fbriere** [comment] 2024-02-20 22:58
- "a readonly username field" is normal, that is by design in edition mode. 
   If you want to edit a different username then you have to edit a different account.
   Each account as its own and unique username.
- "a blank password field" is not normal.
   When you added the regular account in the first place, you specified a non-empty password, right?

**Comment by Saroumane** [comment] 2024-02-20 23:18
> * "a readonly username field" is normal, that is by design in edition mode.
>   If you want to edit a different username then you have to edit a different account.
>   Each account as its own and unique username.
> * "a blank password field" is not normal.
>   When you added the regular account in the first place, you specified a non-empty password, right?

Yes, my password (even with only alphanumeric characters) is immediately erased when I go back to the regular account I just created. Same for all 3 optional fields.
Regarding the username field, I tried to input only in lowercase : it does not help. (And when I go back to the account I just created, it's no longer all lowercase, some letters are uppercase, according my twitter handle)

**Comment by j-fbriere** [comment] 2024-02-20 23:30
@Saroumane Thank you for your explanation. Because of it I think I found the problem! 
Indeed when Squawker add a regular account, behind the scene it will add the actual username of the account as returned by Twitter/X (with lowercases and uppercases) in a database table while at the same time add the username that you entered in the dialog box (with only lowercases) in another database table.
Then the username of the 2 database tables inside Squawker won't match and it will be a problem for Squawker to retrieve the account info later.
Thank you again.

**Comment by Saroumane** [comment] 2024-02-20 23:43
@j-fbriere  Indeed ! When I enter my username exactly like my twitter handle, with 2 uppercase characters, and the rest in lowercase, my credentials are no longer "forgotten" ! In addition, it suddenly display in the interface the 14 credentials I can also see in the json backup. I guess the only way to get rid of them is to edit the json backup and re-import it.

**Comment by j-fbriere** [comment] 2024-02-20 23:50
No need to import the multiple authenticated tokens of the same account. The reason is that the rate limits are in relation to the account, not the authenticated token.
The next version will fix the issue of username lowercases/uppercases and also do some database cleanup when Squawker starts to keep only the most recent authenticated token of each account that has been added.

**Comment by j-fbriere** [comment] 2024-02-22 21:17
Version [v3.7.4](https://github.com/j-fbriere/squawker/releases/tag/v3.7.4) should fix the issue.

**Comment by italoghost** [comment] 2024-02-26 04:27
It has indeed fixed the issue! I will close this one. Thanks, @j-fbriere!

**Closed** 2024-02-26 04:27 UTC
