### ISSUE TITLE
Profile search is hiding nsfw

### ISSUE THREAD

**Issue by CKMz17** [j-fbriere/squawker#162] opened 2024-01-17 22:55 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

3.6.2

### Steps to reproduce the bug

Go to the profile search field
Try to search for some NSFW official profiles

### Actual behavior

No profiles flagged(by Twitter/X?) as nsfw are shown

**Comment by mrhcjones** [comment] 2024-02-18 12:14
This problem might be fixed if you add a regular account to the app

**Comment by j-fbriere** [comment] 2024-02-18 19:22
I confirm that the problem is fixed with a regular account.

**Closed as completed** 2024-02-19 01:30 UTC
Labels: bug
