### ISSUE TITLE
Can't remove/stop using guest accounts after signing in

### ISSUE THREAD

**Issue by Oleepre** [j-fbriere/squawker#192] opened 2024-02-09 02:49 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.7.0+300013473

### Steps to reproduce the bug

1_ Open Squawker.
2_ Go to "Settings -> Account" and make sure there are guest accounts available, if not generate them.
3_ Add a Regular account.
4_ Restart Squawker and notice it still uses guest accounts: rate limit, limited searches, no nsfw tweets, etc.

### Expected behavior

When adding a regular account, Squawker should either disable, ignore or delete current guest accounts and only use the Regular one.

### Actual behavior

 Squawker will always use active guest accounts regardless of the existence of a Regular account.
 Uninstalling and doing a clean install will remove all guest accounts, and adding a Regular one before generating guest ones will work as expected.
 Importing Data that includes X/Twitter tokens causes the same bug, even if they're imported after adding an account.

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung Galaxy A32

**Comment by j-fbriere** [comment] 2024-02-09 03:55
Well it's not a bug because it is by design from my part.

Note: An import never deletes things, it adds or updates things (subs, tokens).

To address your problem, I could add an option to use only regular accounts.

**Comment by Oleepre** [comment] 2024-02-09 05:06
I think a Regular account should take priority after adding it, and as of right now it seems to be ignored until the guest ones expire or we clear the app's data.
 But yeah a toggle to only use one or the other would work.

**Comment by swaggyP36000** [comment] 2024-02-09 07:10
hi, found a temporary fix for this. went a while without using the app so I figured if anyone else is desperate too, they can try this 😭:

- Go to Settings - Data - Export and check everything _except_ "Export Twitter/X Tokens". Save that file anywhere on your device

- Exit out of Squawker and close it from the app switcher, long press the Squawker app icon then click the "i": ![Screenshot_20240209_010516_One UI Home.jpg](https://github.com/j-fbriere/squawker/assets/45519513/701fb4ce-5b15-4436-a733-659668a9be5f) 

- In that page that opens, click Storage, then Clear Data. Then re-open Squawker

- _Before doing anything else_, go to Settings - Account and log in. If you already have a Twitter but it's throwing an error even though your password is correct, it's Twitter flagging it as suspicious. Make a new account. It won't really affect how you browse on Squawker

- Go to Settings - Data and import the backup you created. App should work fine from there

**Comment by j-fbriere** [comment] 2024-02-09 07:30
@swaggyP36000  Thank you for the info.

> If you already have a Twitter but it's throwing an error even though your password is correct, it's Twitter flagging it as suspicious.

Did this happened to you?

**Comment by swaggyP36000** [comment] 2024-02-09 07:47
> @swaggyP36000  Thank you for the info.
> 
> > If you already have a Twitter but it's throwing an error even though your password is correct, it's Twitter flagging it as suspicious.
> 
> Did this happened to you?

yes, but waiting a bit and retrying fixed it. unfortunatelt i dont remember what the error said and I'm not sure i can recreate it (no more accounts to test with). now i have both my main and new one i just made signed in to Squawker

**Comment by j-fbriere** [comment] 2024-02-10 04:56
Version [v3.7.1](https://github.com/j-fbriere/squawker/releases/tag/v3.7.1) implements the functionality to use a different strategy with account types. There are three choices now that can be set in the Account page:
- Prioritize regular account.
- Guest and regular account.
- Only regular account.

**Closed** 2024-02-15 00:31 UTC
Labels: bug
