### ISSUE TITLE
Broken Search/Feed/Trends

### ISSUE THREAD

**Issue by BlanXyz** [j-fbriere/squawker#160] opened 2024-01-16 18:44 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.6.1 (regression)

### Steps to reproduce the bug

1. Go to feed/search/trend page
2. Receive: Error of type _TypeError

### Screenshots/Screen recordings

![Screenshot1](https://github.com/j-fbriere/squawker/assets/83070622/6b124e8c-439b-40cd-81f0-2882b1fcc72f)
![Screenshot2](https://github.com/j-fbriere/squawker/assets/83070622/57cc5627-8c88-41c9-9702-fb8d7b00cc12)

### Affected Android/Custom ROM version

Android 10

**Comment by j-fbriere** [comment] 2024-01-16 19:08
Duplicate of #159.

**Closed** 2024-01-16 19:21 UTC
Labels: bug
