### ISSUE TITLE
Touching the RT account names gives an error.

### ISSUE THREAD

**Issue by rsssxd** [j-fbriere/squawker#13] opened 2023-07-17 11:53 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

V3.1.4

### Steps to reproduce the bug

Find a RT post. Tap the RT account name. 

### Expected behavior

RT account profile should be opened.

### Actual behavior

RT account profile does not open.

### Affected Android/Custom ROM version

LineageOS A10

### Additional information

https://github.com/j-fbriere/squawker/assets/60405617/8ff648c7-3034-4f87-8c94-729777660739

**Comment by j-fbriere** [comment] 2023-07-18 16:46
Since there was no reaction to the fix, I will assume that everything is fine and that the issue is resolved.
Closing the issue.

**Closed by j-fbriere** 2023-07-18 16:46 UTC
Labels: bug

**Comment by rsssxd** [comment] 2023-07-18 16:48
Problem fixed thanks
